// Categories
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'

// Posts
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const SET_POST_SORT_COLUMN = 'SET_POST_SORT_COLUMN'
export const VOTE_POST = 'VOTE_POST'
export const SET_POST_OVERLAY_BLOCK = 'SET_POST_OVERLAY_BLOCK'
export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'

//Comments
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const SET_COMMENT_SORT_COLUMN = 'SET_COMMENT_SORT_COLUMN'
export const VOTE_COMMENT = 'VOTE_COMMENT'
export const SET_COMMENT_OVERLAY_BLOCK = 'SET_COMMENT_OVERLAY_BLOCK'
export const SET_NEW_COMMENT_OVERLAY_BLOCK = 'SET_NEW_COMMENT_OVERLAY_BLOCK'

// User
export const SAVE_USER_NAME = 'SAVE_USER_NAME'